# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_logs', '0002_operation_dday_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb_logs.Operation'),
        ),
    ]
